<h3>Pandas DataFrame Experimentation: 1

Data Source: https://www.kaggle.com/datasets/joycemara/european-fashion-store-multitable-dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load raw data csv:
campaigns_df = pd.read_csv('archive/dataset_fashion_store_campaigns.csv')
channels_df = pd.read_csv('archive/dataset_fashion_store_channels.csv')
customers_df = pd.read_csv('archive/dataset_fashion_store_customers.csv')
products_df = pd.read_csv('archive/dataset_fashion_store_products.csv')
sales_df = pd.read_csv('archive/dataset_fashion_store_sales.csv')
sale_items_df = pd.read_csv('archive/dataset_fashion_store_salesitems.csv')
stock_df = pd.read_csv('archive/dataset_fashion_store_stock.csv')

In [3]:
campaigns_df.head(10)

,campaign_id,campaign_name,start_date,end_date,channel,discount_type,discount_value
0,1,Spring Flash Sale,2025-04-01,2025-04-07,Email,Percentage,10.00%
1,2,Easter Promotion,2025-04-08,2025-04-15,Social Media,Fixed,10
2,3,Mother's Day Campaign,2025-05-01,2025-05-09,Email,Percentage,25.00%
3,4,Mid-Season Clearance,2025-05-10,2025-05-19,App Mobile,Percentage,30.00%
4,5,TIVA Week,2025-05-20,2025-05-31,Social Media,Percentage,30.00%
5,6,June Price Drop,2025-06-01,2025-06-09,Website Banner,Percentage,10.00%
6,7,Early Summer Deals,2025-06-10,2025-06-17,Email,Fixed,12

In [4]:
campaigns_df.tail(10)

,campaign_id,campaign_name,start_date,end_date,channel,discount_type,discount_value
0,1,Spring Flash Sale,2025-04-01,2025-04-07,Email,Percentage,10.00%
1,2,Easter Promotion,2025-04-08,2025-04-15,Social Media,Fixed,10
2,3,Mother's Day Campaign,2025-05-01,2025-05-09,Email,Percentage,25.00%
3,4,Mid-Season Clearance,2025-05-10,2025-05-19,App Mobile,Percentage,30.00%
4,5,TIVA Week,2025-05-20,2025-05-31,Social Media,Percentage,30.00%
5,6,June Price Drop,2025-06-01,2025-06-09,Website Banner,Percentage,10.00%
6,7,Early Summer Deals,2025-06-10,2025-06-17,Email,Fixed,12